[package]
name = "prusti-play"
version = "0.1.0"
authors = ["john"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.prusti-contracts]
git = "https://github.com/viperproject/prusti-dev.git"